server:
  port: 8082

spring:
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payflo_payment}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      payment: payments.events
      order: orders.events
      refund: refunds.events
      settlement: settlements.events

payment:
  order:
    default-order-expiry-minutes: 30
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    methods:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NETBANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      merchant-service:
        base-config: default
      vault-service:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
    instances:
      merchant-service:
        base-config: default
      vault-service:
        base-config: default
