server:
  port: 8083

spring:
  datasource:
    url: ${VAULT_DB_URL:jdbc:postgresql://localhost:5432/payflo_vault}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  master-key: ${VAULT_MASTER_KEY:arXfSlAXS4TRCw5tlKCFSwjG+D4C4ESUV47We3pw2eI=}

resilience4j:
  thread-pool-bulkhead:
    instances:
      vault-card-processor:
        core-thread-pool-size: 10
        max-thread-pool-size: 20
        queue-capacity: 50
