apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/namespace.yaml
  - infra/configmap.yaml
  - stateful/postgres.yaml
  - stateful/redis.yaml
  - stateful/kafka.yaml
  - stateful/kafka-ui.yaml

secretGenerator:
  - name: app-secrets
    namespace: payflo
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
